### ISSUE TITLE
Highlighting the link for the currently shown post 

### ISSUE THREAD

**Issue by githubincronda** [picandocodigo/List-Category-Posts#294]
Hello,
i was wondering if there was a way to highlight the link to the current post with a different color text and/or background when using List Category Posts as a widget in a sidebar?  
Thanks so much for your advice!

**Comment by picandocodigo** [comment]
Hi @githubincronda, when the plugin lists the posts, it uses the `current` CSS class for the current post. It looks something like this:
```html
<li class="current">
  <a href="http://localhost:8080/?p=1300" title="Test LCP">Test LCP</a>
</li>
```

You can edit the color in your theme's CSS with something like this:
```css
.lcp_catlist li.current{
  /* This is the color of the bullet */
  color: #f00;
}

.lcp_catlist li.current a{
  /* This applies to the color of the link */
  color: #0f0;
}
```
